update lecture 9
cornell-dti/trends-in-web-dev-website pull request #189
Opened 2020-12-02 22:19 UTC by jason-tung

Waiting for Megan to add lecture video/update notes on deployment.

- added notes on yarn wkspaces 
- added notes on security

2020-12-02 23:26 UTC, SamChou19815 requested changes

2020-12-02 23:26 UTC, SamChou19815 commented on versioned_docs/version-2020fa/lecture9.md
> +```
we no longer do this in the slides

2020-12-02 23:26 UTC, SamChou19815 commented on versioned_docs/version-2020fa/lecture9.md
> +You can then use the url generated as your backend endpoint in your frontend code.
The slides no longer use global install. Follow the slides. In general, the entire deployment section needs to be rewritten to follow the slides!

2020-12-02 23:26 UTC, SamChou19815 commented on versioned_docs/version-2020fa/lecture9.md
> +We then deployed this app on Firebase for the frontend and Heroku for the backend. Refer to the commands above.
We need some sample code on how to setup package.json for yarn workspaces

2020-12-03 03:23 UTC, meganyin13 commented
@SamChou19815 Jason was waiting on me to add those parts in. Comments should be addressed now

2020-12-03 03:26 UTC, SamChou19815 approved these changes

2020-12-03 03:27 UTC, merged